const factsData = [
    'A year on Mercury is just 88 days long.',
    'Despite being farther from the Sun, Venus experiences higher temperatures than Mercury.',
    'Saturn has the most number of moons in our solar system.',
    'The James Webb Space Telescope (JWST), set to launch in 2021, will be the most powerful space telescope ever built and will help scientists explore the early universe and search for signs of life on other planets.',
    'The concept of "habitable zones" refers to regions around stars where conditions may be suitable for liquid water to exist, potentially allowing for the possibility of life as we know it.',
    'The universe is estimated to be around 13.8 billion years old.',
    'There are more stars in the universe than there are grains of sand on all the beaches on Earth.',
    'The universe is estimated to be around 13.8 billion years old.',
    'There are more stars in the universe than there are grains of sand on all the beaches on Earth.',
    'The largest known star, called UY Scuti, is over 1,700 times larger than our Sun.',
    'The nearest galaxy to our Milky Way is the Andromeda Galaxy, located about 2.5 million light-years away.',
    'The speed of light is approximately 299,792 kilometers per second (or about 186,282 miles per second).',
    'The Sun is so large that approximately 1.3 million Earths could fit inside it.',
    'The Moon is moving away from Earth at a rate of about 3.8 centimeters per year.',
    'Black holes are regions in space where gravity is so strong that nothing, not even light, can escape.',
    'The Milky Way galaxy is estimated to contain over 100 billion stars.',
    'Astronauts in space experience "space sickness" because their inner ears cannot detect up or down without gravity.',
    'Jupiter, the largest planet in our solar system, has a strong gravitational pull that helps protect Earth from some comets and asteroids.',
    'The Great Red Spot on Jupiter is a giant storm that has been raging for over 300 years.',
    "Saturn's rings are made up of countless small particles of ice and rock.",
    'The tallest volcano in our solar system is Olympus Mons on Mars, standing at about 13.6 miles (22 kilometers) high.',
    'Venus has a very thick atmosphere composed mainly of carbon dioxide, making it the hottest planet in our solar system with surface temperatures that can melt lead.',
    'The Hubble Space Telescope has captured some of the most detailed images of distant galaxies and nebulae, expanding our understanding of the universe.',
    'The phenomenon known as a "shooting star" or meteor is actually a small piece of debris burning up as it enters Earth atmosphere.',
    "The International Space Station (ISS) orbits around 400 kilometers (250 miles) above Earth's surface and travels at a speed of approximately 28,000 kilometers per hour (17,500 miles per hour).",
    "The concept of dark matter and dark energy is still a mystery to astronomers, as they make up the majority of the universe's mass and energy but cannot be directly detected.",
    'Astronomers estimate that there areF billions of galaxies in the observable universe, each containing billions of stars.',
    "The largest volcano in the solar system is Olympus Mons on Mars. It stands about 13.6 miles (22 kilometers) high, making it nearly three times the height of Mount Everest.",
    "The Sun contains 99.86% of the total mass of the solar system. It is so massive that it could fit approximately 1.3 million Earths inside it.",
    "The Moon is gradually moving away from Earth at a rate of about 3.8 centimeters per year. This means that in the distant future, the Moon will appear smaller from Earth's perspective.",
    "Saturn's rings are composed of countless small particles, ranging in size from tiny grains to large boulders. These particles are made primarily of ice and rock.",
    "The Andromeda Galaxy, located about 2.5 million light-years away from the Milky Way, is on a collision course with our galaxy. In about 4.5 billion years, the two galaxies will collide and merge.",
    "The concept of 'black holes' was first proposed by physicist John Michell in 1783. These mysterious objects have such strong gravitational pull that nothing, not even light, can escape their grasp.",
    "The largest known star, UY Scuti, is a red hypergiant located in the Milky Way galaxy. It has a radius over 1,700 times that of the Sun, making it one of the largest known stars in the universe.",
    "The concept of 'dark matter' and 'dark energy' remains a mystery in astrophysics. They are believed to make up the majority of the universe's mass and energy but cannot be directly observed or detected.",
    "The speed of light is approximately 299,792 kilometers per second (or about 186,282 miles per second). It is the fastest speed at which information or matter can travel in the universe.",
    "Astronomers estimate that there are billions of galaxies in the observable universe, each containing billions of stars. The sheer vastness of the cosmos is awe-inspiring and leaves much yet to be explored and understood.",
    "Neutron stars are incredibly dense objects that are created when massive stars collapse under their own gravity. A teaspoon of neutron star material would weigh about 10 million tons.",
    "The concept of 'supernovas' refers to the explosive death of a massive star. During a supernova, the star releases an enormous amount of energy and produces elements heavier than iron.",
    "The 'cosmic microwave background radiation' is an echo of the Big Bang, which is still detectable throughout the universe. It provides valuable insights into the early stages of the universe's formation.",
    "Mars has the largest volcano in the solar system called Olympus Mons. It has a diameter of about 370 miles (600 kilometers) and is about 13.6 miles (22 kilometers) high.",
    "Astronauts experience 'space sickness' due to the absence of gravity. It can cause nausea, disorientation, and other symptoms similar to motion sickness.",
    "The 'Kuiper Belt' is a region of the solar system beyond the orbit of Neptune. It is home to numerous icy bodies, including Pluto, which was reclassified as a dwarf planet in 2006.",
    "The 'Hubble Space Telescope' was launched into orbit in 1990 and has provided stunning images and valuable scientific data about distant galaxies, nebulae, and other celestial objects.",
    "The 'Great Red Spot' is a persistent storm on Jupiter that has been observed for over 300 years. It is a large-scale atmospheric phenomenon and is larger than the Earth in diameter.",
    "The 'Milky Way' galaxy is estimated to be about 100,000 light-years in diameter and contains billions of stars. Earth is located in one of its spiral arms, known as the Orion Arm.",
    "'Exoplanets' are planets that orbit stars outside of our solar system. Thousands of exoplanets have been discovered, and some may have the potential to support life."

]

export default factsData;